export const strings = {
    appTitle: 'Words Puzzle',
    cities: 'Cities',
    food: 'Foods',
    animals: 'Animals',
    leadersBoard: 'Leaders Board',
    highScore: 'High Score',
    start: 'START',
    skip: 'SKIP',
    next: 'NEXT',
    home: 'HOME',
    share: 'SHARE',
    successMessage: 'Correct!\nCongratulations',
    newHighScoreMessage: 'New High Score',
    FailureMessage: 'Oops, Wrong Answer',
    earnedPointsMessage: 'Your earned {0}\n points',
    holdOn: 'Hold on!',
    puzzleQuit: 'Are you sure you want to go back?\nYou will loose this game',
    shareScore: 'Hey I am using "Wordly" game, and I have scored {0} points.'
}